version: "2"

output:
  sort-order:
    - linter
    - file # filepath, line, and column.
    - severity

issues:
  # Maximum issues count per one linter, 0 to disable.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text, 0 to disable.
  max-same-issues: 0
  # Make issues output unique by line.
  uniq-by-line: false

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  exclusions:
    generated: strict
  settings:
    gci:
      # Section configuration to compare against.
      # Section names are case-insensitive and may contain parameters in ().
      # The default order of sections is `standard > default > custom > blank > dot > alias > localmodule`.
      # If `custom-order` is `true`, it follows the order of `sections` option.
      # Default: ["standard", "default"]
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        # - prefix(github.com/org/project) # Custom section: groups all imports with the specified Prefix.
        # - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
        # - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
        # - alias # Alias section: contains all alias imports. This section is not present unless explicitly enabled.
        - localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.
      # Checks that no inline comments are present.
      no-inline-comments: true
      # Checks that no prefix comments (comment lines above an import) are present.
      no-prefix-comments: true
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any
        - pattern: a[b:len(a)]
          replacement: a[b:]
    gofumpt:
      extra-rules: true
    goimports:
      # A comma-separated list of prefixes, which, if set, checks import paths
      # with the given prefixes are grouped after 3rd-party packages.
      local-prefixes:
        - github.com/phiryll/lexy
    golines:
      # Target maximum line length.
      max-len: 120
      # Shorten single-line comments.
      shorten-comments: true

linters:
  default: all
  disable:
    # not needed/wanted in this project
    - ginkgolinter      # not using this testing framework
    - gochecknoglobals  # no config options to limit to exported elements
    - goheader          # no headers in source files. LICENSE is enough
    - gomodguard        # depguard is sufficient, this is overkill here
    - makezero          # this is an absurd linter
    - nlreturn          # also absurd, a blank line before every return and branch?
    - promlinter        # metrics collection not used
    - protogetter       # protocol buffers not used
    - rowserrcheck      # SQL not used
    - spancheck         # OpenTelemetry/Census not used
    - thelper           # I need the line numbers
    - varnamelen        # I don't agree with this one most of the time
    - wsl_v5            # might be able to configure this well, but it'll take effort
    # replaced or duplicated
    - gocyclo           # by cyclop
    - lll               # by formatters/golines
    - wsl               # by wsl_v5

  exclusions:
    generated: strict
    rules:
      - path: _test\.go
        linters:
          - dupword
          - gosec
          - prealloc
      - linters:
          - govet
        path: _test\.go
        text: fieldalignment
      - linters:
          - gosec
        path: (big|int)\.go
        text: G115  # integer conversion overflow

  # Settings for specific linters.
  #
  # Setting these to be as strict as possible while still being sane.
  # Using // nolint: ... comments in the code as necessary.
  settings:

    asasalint:
      # To enable/disable the asasalint builtin exclusions of function names.
      # See the default value of `exclude` to get the builtin exclusions.
      use-builtin-exclusions: false

    copyloopvar:
      # Disabled for go version <= 1.21
      # Check all assigning the loop variable to another variable.
      check-alias: true

    cyclop:
      # cyclop annoyingly counts switch statements and if err != nil { ... }.
      # The maximal code complexity to report.
      max-complexity: 15

    decorder:
      # If true, `init` func can be anywhere in file (does not have to be declared before all other functions).
      disable-init-func-first-check: false

    depguard:
      rules:
        main:
          list-mode: strict
          files:
            - !$test
          allow:
            - $gostd
        test:
          list-mode: strict
          files:
            - $test
          allow:
            - $gostd
            - github.com/stretchr/testify
            - github.com/phiryll/lexy

    errcheck:
      # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
      # Such cases aren't reported by default.
      check-blank: true
      # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
      # Such cases aren't reported by default.
      check-type-assertions: true

    errorlint:
      # Permit more than 1 %w verb, valid per Go 1.20 (Requires errorf:true)
      errorf-multi: false

    forbidigo:
      # Instead of matching the literal source code,
      # use type information to replace expressions with strings that contain the package name
      # and (for methods and fields) the type name.
      # This makes it possible to handle import renaming and forbid struct fields and methods.
      analyze-types: true

    funcorder:
      # Checks if the exported methods of a structure are placed before the non-exported ones.
      struct-method: false

    funlen:
      # Ignore comments when counting lines.
      ignore-comments: true

    gocognit:
      # Minimal code complexity to report.
      min-complexity: 20

    goconst:
      # Ignore when constant is not used as function argument.
      ignore-calls: false
      # Detects constants with identical values.
      find-duplicates: true
      # Ignore strings from test files.
      ignore-tests: true

    gocritic:
      enable-all: true
      disabled-checks:
        - commentedOutCode
        - whyNoLint
        - unnamedResult
      # Settings passed to gocritic.
      # The settings key is the name of a supported gocritic checker.
      # The list of supported checkers can be find in https://go-critic.github.io/overview.
      settings:
        captLocal:  # don't capitalize local variable names
          # Whether to restrict checker to params only.
          paramsOnly: false
        elseif:  # use if ... elseif .. instead of if ... else { if ...
          # Whether to skip balanced if-else pairs.
          skipBalanced: false
        hugeParam:
          # Size in bytes that makes the warning trigger.
          sizeThreshold: 64
        nestingReduce:
          # Min number of statements inside a branch to trigger a warning.
          bodyWidth: 2
        rangeExprCopy:
          # Size in bytes that makes the warning trigger.
          sizeThreshold: 64
          # Whether to check test functions
          skipTestFuncs: false
        rangeValCopy:
          # Size in bytes that makes the warning trigger.
          sizeThreshold: 64
        tooManyResultsChecker:
          # Maximum number of results.
          maxResults: 3
        truncateCmp:
          # Whether to skip int/uint/uintptr types.
          skipArchDependent: false
        underef:
          # Whether to skip (*x).method() calls where x is a pointer receiver.
          skipRecvDeref: false

    gosec:
      # To specify the configuration of rules.
      config:
        # Globals are applicable to all rules.
        global:
          # Audit mode enables addition checks that for normal code analysis might be too nosy.
          audit: true
        G101:
          # If true, complain about all cases (even with low entropy).
          ignore_entropy: true

    govet:
      enable-all: true

    importas:
      # Do not allow non-required aliases.
      no-extra-aliases: true

    ireturn:
      # keywords:
      # - `empty` for `interface{}`
      # - `error` for errors
      # - `stdlib` for standard library
      # - `anon` for anonymous interfaces
      # - `generic` for generic interfaces added in go 1.18

      # By default, it allows using errors, empty interfaces, anonymous interfaces,
      # and interfaces provided by the standard library.
      allow:
        - error
        - generic

    maintidx:
      # Show functions with maintainability index lower than N.
      # A high index indicates better maintainability (it's kind of the opposite of complexity).
      under: 30

    nakedret:
      # Make an issue if func has more lines of code than this setting, and it has naked returns.
      max-func-lines: 0

    nestif:
      # Minimal complexity of if statements to report.
      min-complexity: 3

    nolintlint:
      # Enable to require nolint directives to mention the specific linter being suppressed.
      require-specific: true

    nonamedreturns:
      # Report named error if it is assigned inside defer.
      report-error-in-defer: true

    prealloc:
      # Report pre-allocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them.
      simple: false
      # Report pre-allocation suggestions on for loops.
      for-loops: true

    predeclared:
      # Include method names and field names (i.e., qualified names) in checks.
      qualified-name: true

    reassign:
      # Patterns for global variable names that are checked for reassignment.
      # See https://github.com/curioswitch/go-reassign#usage
      patterns:
        - .*

    revive:

      # Linting errors with less than this confidence will be ignored.
      confidence: 0.6

      # Enable all available rules.
      enable-all-rules: true

      # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md
      rules:
        - name: add-constant          # duplicated by mnd
          disabled: true
        - name: bare-return           # duplicated by nakedret
          disabled: true
        - name: cognitive-complexity  # duplicated by gocognit
          disabled: true
        - name: cyclomatic            # duplicated by cyclop
          disabled: true
        - name: function-length       # duplicated by funlen
          disabled: true
        - name: line-length-limit     # duplicated by formatters/golines
          disabled: true
        - name: comment-spacings      # configuration of this rule does not work, and gofmt should fix it anyway.
          disabled: true
        - name: confusing-naming      # can't handle multiple implementations of an interface
          disabled: true
        - name: confusing-results     # uses here are not really problematic
          disabled: true
        - name: file-header           # not using file headers
          disabled: true
        - name: max-public-structs    # don't know how to limit to one file
          disabled: true

        - name: enforce-map-style
          arguments:
            - literal
        - name: enforce-repeated-arg-type-style
          arguments:
            - short
        - name: enforce-slice-style
          arguments:
            - literal
        - name: max-control-nesting
          arguments:
            - 3
        - name: unhandled-error
          arguments:
            - fmt.Printf
            - fmt.Println

    testifylint:
      # Enable all checkers (https://github.com/Antonboom/testifylint#checkers).
      enable-all: true
      disable:
        - float-compare
        - require-error

    testpackage:
      # List of packages that don't end with _test that tests are allowed to be in.
      allow-packages: []

    unconvert:
      # Remove conversions that force intermediate rounding.
      fast-math: true

    usestdlibvars:
      # Suggest the use of time.Month.String().
      time-month: true
      # Suggest the use of time.Layout.
      time-layout: true
      # Suggest the use of constant.Kind.String().
      constant-kind: true
