name: Actions for non-draft releases

on:
  push:
  # release:
  #  types: [published]
  # push:
  #  tags:
  #    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Publish to pkg.go.dev
        run: |
          echo "ref_name ${{ github.ref_name }}"
          echo "ref ${{ github.ref }}"
        # run: GOPROXY=proxy.golang.org go list -m github.com/phiryll/lexy@${{  }}
        # run: curl "https://proxy.golang.org/github.com/phiryll/lexy/@v/${{  }}.info"
