name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        # Currently having linter issues with 1.23.0,
        # so it's safest to limit this version as well.
        go: ['1.19', '1.22.6']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - run: go build -v ./...
    - run: go vet ./...
    - run: go test -v ./...
